news = {
    "status": "ok",
    "total_hits": 10000,
    "page": 1,
    "total_pages": 200,
    "page_size": 50,
    "articles": [
        {
            "summary": "ROTSELAAR &#8212; A 103-year-old Belgian doctor is walking a marathon around his garden in daily stages to raise money for research into the new coronavirus, inspired by a centenarian who became a hero in Britain for clocking up the charity miles with a walking frame. Alfons Leempoels, a retired general practitioner, started his 42.2 km [&#8230;]",
            "country": "CA",
            "clean_url": "canoe.com",
            "author": "Reuters",
            "rights": None,
            "link": "https://canoe.com/news/world/belgian-aged-103-walking-marathon-to-raise-funds-for-covid-19-research",
            "rank": "9301",
            "topic": "NA",
            "language": "en",
            "title": "Belgian, 103, walking marathon to raise funds for COVID-19 research",
            "published_date": "2020-06-09 16:24:54",
            "_id": "6a7b63a5fb2284398bc1461af6ace3b0",
            "_score": 3.0822992
        },
        {
            "summary": "South Africa warns pandemic could last up to two years; Indonesia reports largest daily rise in infections\n\n\nCoronavirus – latest updates\n\nSee all our coronavirus coverage\n\n\nMoscow has partially lifted its lockdown despite Russia reporting thousands of new cases daily and Spain's government said facemasks would remain mandatory in public, as Europe continued to emerge from the long first phase of its struggle against Covid-19.\n\nConcern mounted, however, over the spread of the coronavirus in Africa and elsewhere, with Nigeria confirming 600 deaths from previously undetected outbreak and South Africa warning its epidemic could last up to two years.\n\nThe coronavirus has infected more than 7,155,000 people worldwide and killed more than 407,000, according to the Johns Hopkins university tracker.\n\nNearly one in five Iranians – 15 million – may have been infected with the virus since the country's outbreak started in February, a health official said.\n\nIsrael's internal security service, Shin Bet, has halted its controversial mobile phone tracking of virus carriers, saying the method was no longer required.\n\nThe virus may have been present and spreading in Wuhan, China as early as last summer, according to US researchers who found a 'steep increase” in cars outside the city's hospitals between August and December 2019.\n\nSpain is not discussing any travel corridor with the UK, a foreign ministry source said, but hopes the EU will agree on common criteria to allow tourists to travel.\n\nSlovakia is to reopen its borders to 16 more European countries from 10 June and will no longer require people to wear face masks outside.\n\nA UN expert said that food insecurity in North Korea, which has yet to confirm a case, was deepening and some people were 'starving” due to its Covid-19 measures.\n Continue reading...",
            "country": "AU",
            "clean_url": "theguardian.com",
            "author": "Jon Henley",
            "rights": "Guardian News &amp; Media Limited or its affiliated companies. All rights reserved. 2020",
            "link": "https://www.theguardian.com/world/2020/jun/09/global-report-moscow-relaxes-lockdown-despite-high-caseload-nigerian-deaths-rise",
            "rank": "56",
            "topic": "NA",
            "language": "en",
            "title": "Global report: Moscow relaxes lockdown despite high caseload; Nigerian deaths rise",
            "published_date": "2020-06-09 16:21:22",
            "_id": "fdbfceebd6f5435a11288b510ac4a4c4",
            "_score": 2.7033331
        },
        {
            "summary": "",
            "country": "NA",
            "clean_url": "indianexpress.com",
            "author": "",
            "rights": None,
            "link": "https://indianexpress.com/article/cities/delhi/delhi-govt-panel-suggests-use-of-stadiums-as-makeshift-covid-facilities-6450911/",
            "rank": "1345",
            "topic": "NA",
            "language": "en",
            "title": "Delhi govt panel suggests use of stadiums as makeshift COVID facilities",
            "published_date": "2020-06-09 16:20:41",
            "_id": "5a0bdef940fb2273946c7f93908f65dd",
            "_score": 4.321634
        },
        {
            "summary": "Pennsylvania on Tuesday reported 61 more covid-19 deaths and 493 additional cases, bringing the state’s total number of cases to 76,436, according to state health officials.",
            "country": "NA",
            "clean_url": "triblive.com",
            "author": "Patrick Varine",
            "rights": None,
            "link": "https://triblive.com/news/pennsylvania/state-reports-493-additional-covid-cases-61-new-deaths/",
            "rank": "3574",
            "topic": "NA",
            "language": "en",
            "title": "Pennsylvania coronavirus death toll tops 6,000; 493 new cases reported",
            "published_date": "2020-06-09 16:20:01",
            "_id": "81dff3dce31dc319a1cff314b6877476",
            "_score": 3.6304083
        },
        {
            "summary": "State health officials reported the 100th death Tuesday, as well as 18 new cases as expanded testing continues.",
            "country": "NA",
            "clean_url": "pressherald.com",
            "author": "Joe Lawlor",
            "rights": None,
            "link": "https://www.pressherald.com/2020/06/09/maine-marks-100th-death-from-covid-19/",
            "rank": "3355",
            "topic": "NA",
            "language": "en",
            "title": "Maine marks 100th death from COVID-19",
            "published_date": "2020-06-09 16:19:06",
            "_id": "7e64dd597721c4b9861943cff62a4f06",
            "_score": 3.8795485
        },
        {
            "summary": "India is better positioned in the fight against Covid-19 compared to other countries but there is no space for complacency, Union health minister harsh Vardhan said on Tuesday as the death toll due to coronavirus infection rose to 7,466 and the cases mounted to 2,66,598 in the country.",
            "country": "IN",
            "clean_url": "indiatimes.com",
            "author": None,
            "rights": "Copyright:(C) 2020 Bennett Coleman & Co. Ltd, http://in.indiatimes.com/policyterms/1554651.cms",
            "link": "https://timesofindia.indiatimes.com/india/india-better-positioned-in-fight-against-covid-19-but-no-space-for-complacency-harsh-vardhan/articleshow/76284558.cms",
            "rank": "330",
            "topic": "NA",
            "language": "en",
            "title": "India better positioned in fight against Covid-19 but no space for complacency: Harsh Vardhan",
            "published_date": "2020-06-09 16:18:43",
            "_id": "ae069dbc0e35964d5d71c942d03ddc7b",
            "_score": 4.379669
        },
        {
            "summary": "HARRISON TWP, MI &#x97; Residents in southeastern Michigan will celebrate President Donald Trump&#x92;s 74th birthday with a boat parade. The Michigan Conservative Coalition and Michigan Trump Republicans 2020 are hosting the &#x22;Make American Great Again&#x22; parade Saturday afternoon. The boat parade will start at MacRay Harbor marina in Macomb County&#x27;s Harrison Township and end near the Ambassador Bridge in Detroit, the Associated Press reports. Trump&#x27;s birthday is June 14. Matt Seely, spokesman for the coalition, said organizers are anticipating that nearly 1,000 people will attend. &#x22;Truthfully, with everything we&#x27;ve been through (with) the COVID-19 crisis, I think that people are...",
            "country": "NA",
            "clean_url": "freerepublic.com",
            "author": "mlive.com",
            "rights": None,
            "link": "https://www.freerepublic.com/focus/f-news/3853749/posts",
            "rank": "3975",
            "topic": "news",
            "language": "en",
            "title": "Boat parade planned in southeast Michigan to celebrate President Trump&#x92;s birthday",
            "published_date": "2020-06-09 16:18:07",
            "_id": "e738b3cdb45a460392b285bd6b0fd32d",
            "_score": 2.6630702
        },
        {
            "summary": "No strategy 'utterly insulates” Ireland from the coronavirus, the Covid-19 Oireachtas committee was told on Tuesday.\n  \nChair of the Irish Epidemiology Modelling Advisory Group Prof Philip Nolan said the best way to suppress the virus was to adhere to the public health guidance including maintaining social distancing.\n  \nHe rejected the view that 'if only we had testing and tracing and a facemask we could do all the other things we used to do”.\n  \nProf Nolan was being questioned about a letter signed by dozens of researchers, scientists and medics calling for a different policy of 'crushing” the virus rather than trying to live with it. \n  \nProf Nolan said that 'different scientists have different judgments in the face of incomplete evidence”.\n  \nHe said the strategy was not one of mitigation or living with an ongoing or significant levels of transmission but of suppression.\n  \nProf Nolan said he fully supported the recommendations of the NPHET. 'I support them and they accord with my judgment. No strategy utterly insulates us from the virus.”\n  \nHe told Fianna Fáil health spokesman Stephen Donnelly that there will be renewed outbreaks of Covid-19 disease across Europe which would be in 'small waves”.\n  \nProf Nolan also told the committee that 'the management of the second wave will be different from the first wave. There could be more targeted measures introduced to control future outbreak”.\n  \nAsked by Mr Donnelly if Irish society will be fully functioning by the end of the year, Prof Nolan said, 'I don't have a crystal ball on this and could not give a probability on the likelihood”.\n  \n'Our behaviour will continue to be modified by this virus for some time to come.”",
            "country": "IE",
            "clean_url": "irishtimes.com",
            "author": None,
            "rights": None,
            "link": "https://www.irishtimes.com/news/health/no-strategy-utterly-insulates-ireland-from-covid-19-committee-told-1.4274834?localLinksEnabled=false",
            "rank": "922",
            "topic": "NA",
            "language": "en",
            "title": "No strategy ‘utterly insulates' Ireland from Covid-19, committee told",
            "published_date": "2020-06-09 16:17:53",
            "_id": "d279ae3b81e9cf52ebdc3b5ea958f348",
            "_score": 3.358306
        },
        {
            "summary": "WWE Champion Drew McIntyre recently spoke with Jonathan Snowden of WrestleJoy and looked ahead to when WWE will be able to have fans back at their events amid the coronavirus pandemic. McIntyre has been WWE Champion for going on 70 days now but he’s yet to step in a ring\n \nThe post Drew McIntyre on Where He Stands as WWE Champion During the COVID-19 Era, How It Will Feel When Fans Return appeared first on WrestlingHeadlines.com.",
            "country": "NA",
            "clean_url": "lordsofpain.net",
            "author": "Marc Middleton",
            "rights": None,
            "link": "https://wrestlingheadlines.com/drew-mcintyre-on-where-he-stands-as-wwe-champion-during-the-covid-19-era-how-it-will-feel-when-fans-return/",
            "rank": "160246",
            "topic": "NA",
            "language": "en",
            "title": "Drew McIntyre on Where He Stands as WWE Champion During the COVID-19 Era, How It Will Feel When Fans Return",
            "published_date": "2020-06-09 16:17:45",
            "_id": "e601cf2025dd5b5d87a9029dd5fd11db",
            "_score": 3.0427008
        },
        {
            "summary": "Clairwood Secondary School will remain closed until further notice after a teacher tested positive for Covid-19. Earlier on Tuesday, Apollo Secondary School in Chatsworth confirmed that a teacher has also tested positive.",
            "country": "ZA",
            "clean_url": "iol.co.za",
            "author": "Se-Anne Rall",
            "rights": "INDEPENDENT MEDIA",
            "link": "https://www.iol.co.za/news/south-africa/kwazulu-natal/second-durban-high-school-closes-after-teacher-tests-positive-for-covid-19-49168610",
            "rank": "2155",
            "topic": "NA",
            "language": "en",
            "title": "Second Durban high school closes after teacher tests positive for Covid-19",
            "published_date": "2020-06-09 16:16:00",
            "_id": "57da27d7f0dc0e3f5fa478db2d88425f",
            "_score": 4.3332005
        },
        {
            "summary": "GENEVA — A top World Health Organization expert has tried to clear up 'misunderstandings” about comments she made that were widely understood to suggest that people without COVID-19 symptoms rarely transmit the coronnoavirus.",
            "country": "NA",
            "clean_url": "roanoke.com",
            "author": "By The Associated Press",
            "rights": None,
            "link": "https://www.roanoke.com/business/the-latest-who-expert-clarifies-remarks-on-virus-spread/article_586b14b8-2f1d-5ea5-8937-2d97d8d9c7d3.html",
            "rank": "6972",
            "topic": "news",
            "language": "en",
            "title": "The Latest: WHO expert clarifies remarks on virus spread",
            "published_date": "2020-06-09 16:15:15",
            "_id": "3df06177ad7c0107d43c460255782fb4",
            "_score": 3.446394
        },
        {
            "summary": "GENEVA — A top World Health Organization expert has tried to clear up 'misunderstandings” about comments she made that were widely understood to suggest that people without COVID-19 symptoms rarely transmit the coronnoavirus.",
            "country": "NA",
            "clean_url": "dailyprogress.com",
            "author": "By The Associated Press",
            "rights": None,
            "link": "https://www.dailyprogress.com/business/the-latest-who-expert-clarifies-remarks-on-virus-spread/article_c2640f9e-61a7-5368-9f75-0d9cd2126d67.html",
            "rank": "11306",
            "topic": "news",
            "language": "en",
            "title": "The Latest: WHO expert clarifies remarks on virus spread",
            "published_date": "2020-06-09 16:15:15",
            "_id": "aa35efae5bbe6462aa2b60b18f385686",
            "_score": 3.3368306
        },
        {
            "summary": "GENEVA — A top World Health Organization expert has tried to clear up 'misunderstandings” about comments she made that were widely understood to suggest that people without COVID-19 symptoms rarely transmit the coronnoavirus.",
            "country": "NA",
            "clean_url": "nptelegraph.com",
            "author": "By The Associated Press",
            "rights": None,
            "link": "https://www.nptelegraph.com/business/the-latest-who-expert-clarifies-remarks-on-virus-spread/article_0d0347e2-03e5-5ed6-a683-9c69107812de.html",
            "rank": "83360",
            "topic": "NA",
            "language": "en",
            "title": "The Latest: WHO expert clarifies remarks on virus spread",
            "published_date": "2020-06-09 16:15:15",
            "_id": "0802f5a9dcab13756617235fdf750326",
            "_score": 2.9088383
        },
        {
            "summary": "&lt;p xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;span class=&quot;xn-location&quot;&gt;DUBLIN, &lt;span class=&quot;xn-chron&quot;&gt;June 9, 2020 /PRNewswire/ -- The &quot;Asphalt - Global Market Trajectory &amp; Analytics&quot; report has been added to &lt;b&gt;ResearchAndMarkets.com&#39;s&lt;/b&gt; offering. &lt;p xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;Amid the COVID-19 crisis and the looming economic recession,...",
            "country": "NA",
            "clean_url": "finanzen.ch",
            "author": None,
            "rights": "finanzen.net GmbH",
            "link": "https://www.finanzen.ch/nachrichten/aktien/the-global-asphalt-market-analysis-and-forecasts-2020-2027-featuring-atlas-roofing-corporation-bp-plc-crh-plc-and-exxon-mobil-corporation-1029293920",
            "rank": "96210",
            "topic": "finance",
            "language": "en",
            "title": "The Global Asphalt Market Analysis and Forecasts 2020-2027, Featuring Atlas Roofing Corporation, BP Plc, CRH Plc and Exxon Mobil Corporation",
            "published_date": "2020-06-09 16:15:00",
            "_id": "800c2e145e750fbcdb520fbe765c404d",
            "_score": 2.0844886
        },
        {
            "summary": "The Pennsylvania Department of Health Tuesday confirmed as of 12:00 a.m., June 9, that there are 493 additional positive cases of COVID-19, bringing the statewide total to 76,436. \n       \nThere are 6,014 total deaths attributed to COVID-19, an increase of 61 new deaths.",
            "country": "NA",
            "clean_url": "standardspeaker.com",
            "author": "Staff report",
            "rights": None,
            "link": "http://www.standardspeaker.com/news/carbon-luzerne-and-schuylkill-counties-meet-several-state-reopening-metrics-1.2636834",
            "rank": "77819",
            "topic": "news",
            "language": "en",
            "title": "Carbon, Luzerne and Schuylkill counties meet several state reopening metrics",
            "published_date": "2020-06-09 16:14:05",
            "_id": "7df82387b624c347ffb9e1e7ba3ba526",
            "_score": 3.5745077
        },
        {
            "summary": "A report released by the Eastern Cape COVID-19 command council showed that from 1 June to 7 June, 94 murder cases were recorded in the province.",
            "country": "ZA",
            "clean_url": "ewn.co.za",
            "author": None,
            "rights": None,
            "link": "https://ewn.co.za/2020/06/09/ec-govt-formally-requests-reinstatement-of-lockdown-alcohol-ban",
            "rank": "12734",
            "topic": "news",
            "language": "en",
            "title": "EC govt formally requests reinstatement of lockdown alcohol ban",
            "published_date": "2020-06-09 16:13:07",
            "_id": "30f472e928ee1daa78be299a046f95c5",
            "_score": 3.4410205
        },
        {
            "summary": "One of the most obvious impacts of the Covid-19 pandemic is how reliant we have all become on connectivity, particularly wireless connectivity. For most of us, the combination of a fast broadband connection along with a solid Wi-Fi wireless network inside our home has literally made the difference between being...",
            "country": "NA",
            "clean_url": "techspot.com",
            "author": "Bob O'Donnell",
            "rights": "Copyright 2020 TechSpot, Inc. The contents of this feed are available for non-commercial use only.",
            "link": "https://www.techspot.com/news/85550-opinion-wi-fi-6e-opens-new-possibilities-fast.html",
            "rank": "2993",
            "topic": "tech",
            "language": "en",
            "title": "Opinion: Wi-Fi 6E opens new possibilities for fast wireless connectivity",
            "published_date": "2020-06-09 16:13:00",
            "_id": "dd97382bd8f981a0c0f285735dd34ee5",
            "_score": 3.3232684
        },
        {
            "summary": "Insisting that Union home minister Amit Shah's speech at the BJP's virtual rally for West Bengal was \"devoid of substance\", the TMC on Tuesday said the saffron party was \"hungry for votes\" even when the state was battling the double whammy of Covid-19 and destruction caused by Cyclone Amphan.",
            "country": "IN",
            "clean_url": "indiatimes.com",
            "author": None,
            "rights": "Copyright:(C) 2020 Bennett Coleman & Co. Ltd, http://in.indiatimes.com/policyterms/1554651.cms",
            "link": "https://timesofindia.indiatimes.com/india/amit-shahs-speech-devoid-of-substance-bjp-hungry-for-votes-amid-pandemic-tmc/articleshow/76283980.cms",
            "rank": "330",
            "topic": "NA",
            "language": "en",
            "title": "Amit Shah's speech 'devoid of substance', BJP 'hungry for votes' amid pandemic: TMC",
            "published_date": "2020-06-09 16:12:36",
            "_id": "a96b818337ec3b1297523d6d062eb0f0",
            "_score": 3.5278041
        },
        {
            "summary": "The death of one more patient in the last 24 hours brought Greece’s Covid-19 death toll to 183, the Health Ministry said in its briefing on Tuesday.",
            "country": "NA",
            "clean_url": "ekathimerini.com",
            "author": None,
            "rights": "None None",
            "link": "http://www.ekathimerini.com/253506/article/ekathimerini/news/nine-new-covid-19-infections-one-death",
            "rank": "7106",
            "topic": "NA",
            "language": "en",
            "title": "Nine new Covid-19 infections, one death",
            "published_date": "2020-06-09 16:12:17",
            "_id": "964eca3e7886a9889e0c75ce481516a2",
            "_score": 4.323306
        },
        {
            "summary": "Edo Government has called on all political parties in the state to obey and follow the laid down rules in the Gazette curtailing the spread of COVID-19 during the conduct of their primaries.\n \nThe post Edo :Be law-abiding in conducting primaries, Dep.Gov tasks political parties appeared first on Vanguard News.",
            "country": "NA",
            "clean_url": "vanguardngr.com",
            "author": "Urowayino Jeremiah",
            "rights": None,
            "link": "https://www.vanguardngr.com/2020/06/edo-be-law-abiding-in-conducting-primaries-dep-gov-tasks-political-parties/",
            "rank": "6385",
            "topic": "NA",
            "language": "en",
            "title": "Edo :Be law-abiding in conducting primaries, Dep.Gov tasks political parties",
            "published_date": "2020-06-09 16:12:17",
            "_id": "e3a2d7b9218d8251ef74ba2f6878a8b5",
            "_score": 3.2327504
        },
        {
            "summary": "&lt;p xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;span class=&quot;xn-location&quot;&gt;TUCSON, Ariz., &lt;span class=&quot;xn-chron&quot;&gt;June 9, 2020 /PRNewswire/ -- Metropia, Inc. announced enhancements to its GoEzy trip planning app to address traveller concerns and enhance passenger safety in light of the Covid-19 pandemic.&#160;&lt;p xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;Across...",
            "country": "NA",
            "clean_url": "finanzen.ch",
            "author": None,
            "rights": "finanzen.net GmbH",
            "link": "https://www.finanzen.ch/nachrichten/aktien/metropia-adds-covid-19-feature-set-to-its-goezy-trip-planner-app-1029293917",
            "rank": "96210",
            "topic": "finance",
            "language": "en",
            "title": "Metropia adds Covid-19 feature set to its GoEzy trip planner app",
            "published_date": "2020-06-09 16:11:00",
            "_id": "c1aaf499a1969767009a00c22a6d4630",
            "_score": 3.0477314
        },
        {
            "summary": "By Paul Olayemi A pastor who was allegedly smuggled into a private hospital in Sapele, Delta State on Saturday, after he developed Coronavirus complications has reportedly died Monday night while awaiting evacuation after the hospital was closed by the Delta State Ministry of Health monitoring team. The pastor, Wilson Okotie, Senior Pastor, High Impact Christian\nRead More\n \nThe post Another Pastor dies of COVID-19 in Delta, as state govt seals clinic appeared first on Vanguard News.",
            "country": "NA",
            "clean_url": "vanguardngr.com",
            "author": "Temisan Amoye",
            "rights": None,
            "link": "https://www.vanguardngr.com/2020/06/another-pastor-dies-of-covid-19-in-delta-as-state-govt-seals-clinic/",
            "rank": "6385",
            "topic": "NA",
            "language": "en",
            "title": "Another Pastor dies of COVID-19 in Delta, as state govt seals clinic",
            "published_date": "2020-06-09 16:10:05",
            "_id": "f03f34fa0abf4e940b29212fa20c124b",
            "_score": 3.7201686
        },
        {
            "summary": "Kindly Share This Story: By Paul Olayemi A pastor who was allegedly smuggled into a private hospital in Sapele, Delta State on Saturday, after he developed Coronavirus",
            "country": "NA",
            "clean_url": "onlinenigeria.com",
            "author": None,
            "rights": "© 2012 Spoonlabs d.o.o.",
            "link": "https://news2.onlinenigeria.com/news/general/834458-another-pastor-dies-of-covid-19-in-delta-as-state-govt-seals-clinic.html",
            "rank": "111023",
            "topic": "NA",
            "language": "en",
            "title": "Another Pastor dies of COVID-19 in Delta, as state govt seals clinic",
            "published_date": "2020-06-09 16:10:00",
            "_id": "923eb16ff3f91a81b3f3315c8bbe8239",
            "_score": 2.9828072
        },
        {
            "summary": "Nursing homes banned all visitors and nonessential workers from nursing homes in mid-March to stop the spread of COVID-19. Advocates and families want that ban to end.",
            "country": "NA",
            "clean_url": "npr.org",
            "author": "Ina Jaffe",
            "rights": "Copyright 2020 NPR - For Personal Use Only",
            "link": "https://www.npr.org/2020/06/09/870159589/banned-from-nursing-homes-families-see-shocking-decline-in-their-loved-ones?utm_medium=RSS&utm_campaign=news",
            "rank": "148",
            "topic": "news",
            "language": "en",
            "title": "Banned From Nursing Homes, Families See Shocking Decline In Their Loved Ones",
            "published_date": "2020-06-09 16:09:27",
            "_id": "2dc191fbff3964689bf9ad1930e2e8c0",
            "_score": 3.7993588
        },
        {
            "summary": "The Lincoln County Jail will begin accepting arrestees for more charges on June 9th. Through continued community partnerships the Lincoln County Jail has been able to verify through testing if an Adult In Custody (AIC) is COVID-19 positive or negative prior to housing.  With that in mind, there is still a real concern based on [&#8230;]",
            "country": "NA",
            "clean_url": "newslincolncounty.com",
            "author": "Dave Morgan",
            "rights": None,
            "link": "https://www.newslincolncounty.com/archives/248271?utm_source=rss&utm_medium=rss&utm_campaign=changes-emerge-at-the-lincoln-county-jail",
            "rank": "872925",
            "topic": "news",
            "language": "en",
            "title": "Changes emerge at the Lincoln County Jail",
            "published_date": "2020-06-09 16:08:40",
            "_id": "c61ccbb1b89424b0d902243cc6b0b822",
            "_score": 2.602873
        },
        {
            "summary": "Civil rights groups and the state have two weeks to come up with a plan to test every person incarcerated in North Carolina. Judge Vinston Rozier Jr. of Wake County Superior Court ruled Monday that the conditions inside North Carolina's prisons were likely unconstitutional due to the state's failure to provide substantial testing for COVID-19 to people in its prisons and for not following public health guidelines for limiting the spread of disease.",
            "country": "NA",
            "clean_url": "wfae.org",
            "author": "Jordan Wilkie / Carolina Public Press",
            "rights": "NPR Digital Services RSS Generator 0.94",
            "link": "https://www.wfae.org/post/judge-prison-conditions-during-pandemic-likely-unconstitutional",
            "rank": "34072",
            "topic": "news",
            "language": "en",
            "title": "Judge: Prison Conditions During Pandemic Likely Unconstitutional",
            "published_date": "2020-06-09 16:08:30",
            "_id": "7541a643c131a463bf5a38d0a24aba6e",
            "_score": 2.672877
        },
        {
            "summary": "Google Maps is now providing added Covid 19 related details to ensure users have a more hassle-free experience while traveling. The update becomes relevant at a time when the world is trying to come to terms with life while the pandemic continues unabated in several parts of the world. Among the new features Google Maps […]",
            "country": "NA",
            "clean_url": "inferse.com",
            "author": "Sovan Mandal",
            "rights": None,
            "link": "https://www.inferse.com/56962/google-maps-offering-travel-info-on-restrictions-and-facilities-during-covid-19-pandemic/",
            "rank": "435678",
            "topic": "tech",
            "language": "en",
            "title": "Google Maps offering travel info on restrictions and facilities during Covid 19 pandemic",
            "published_date": "2020-06-09 16:08:16",
            "_id": "0b1c57647a355d6b7a84ae2d8b69fd3b",
            "_score": 3.2811224
        },
        {
            "summary": "FRANKFURT &#8212; GlaxoSmithKline (GSK) has started a trial in the United States to test an experimental rheumatoid arthritis drug on patients suffering from pneumonia caused by COVID-19, the British drugmaker said on Tuesday. The company said it plans to expand trial activity to sites in the United Kingdom, Italy, Spain, South America and Africa. GSK, [&#8230;]",
            "country": "CA",
            "clean_url": "financialpost.com",
            "author": "Reuters",
            "rights": None,
            "link": "https://business.financialpost.com/pmn/business-pmn/gsk-begins-u-s-test-of-experimental-drug-for-pneumonia-from-covid-19",
            "rank": "1898",
            "topic": "news",
            "language": "en",
            "title": "GSK begins U.S. test of experimental drug for pneumonia from COVID-19",
            "published_date": "2020-06-09 16:07:25",
            "_id": "7b2f246ff6b1ae69f136d5043ed5b347",
            "_score": 4.1415567
        },
        {
            "summary": "A group of four parents on Tuesday moved the Supreme Court against CBSE's decision to hold the remaining examination of the Board(XII) from July 1 onwards and pleaded the court to direct that students be given marks on the basis of internal assessment in view of COVID-19 pandemic.",
            "country": "IN",
            "clean_url": "indiatimes.com",
            "author": None,
            "rights": "Copyright:(C) 2020 Bennett Coleman & Co. Ltd, http://in.indiatimes.com/policyterms/1554651.cms",
            "link": "https://timesofindia.indiatimes.com/india/parents-move-sc-against-cbses-decision-to-hold-remaining-board-exam/articleshow/76284211.cms",
            "rank": "330",
            "topic": "NA",
            "language": "en",
            "title": "Parents move SC against CBSE's decision to hold remaining Board exam",
            "published_date": "2020-06-09 16:06:48",
            "_id": "416f7bc1840b10b13d2876730b8a50d7",
            "_score": 3.564738
        },
        {
            "summary": "TORONTO, June  09, 2020  (GLOBE NEWSWIRE) -- Revive Therapeutics Ltd. ('Revive” or the 'Company”) (CSE: RVV), a specialty life sciences company focused on the research and development of therapeutics for medical needs and rare disorders, is pleased to announce that the Company met with Health Canada in a Pre-Clinical Trial Application ('Pre-CTA”) meeting to evaluate the potential of a clinical study of Bucillamine in the treatment of patients with mild-moderate COVID-19 due to the SARS-CoV-2 infection in Canada.",
            "country": "NA",
            "clean_url": "globenewswire.com",
            "author": None,
            "rights": None,
            "link": "http://www.globenewswire.com/news-release/2020/06/09/2045848/0/en/Revive-Therapeutics-Provides-Update-on-Discussions-with-Health-Canada-in-Pre-CTA-Meeting.html",
            "rank": "917",
            "topic": "NA",
            "language": "en",
            "title": "Revive Therapeutics Provides Update on Discussions with Health Canada in Pre-CTA Meeting",
            "published_date": "2020-06-09 16:06:00",
            "_id": "2f194cdc4770640c57def335db7ce8e1",
            "_score": 3.176168
        },
        {
            "summary": "Country: World\n                 \nSources: World Food Programme, Logistics Cluster\n                                 \n\n                                 \nBackground\n  \nIn an effort to have an overview of the impact of COVID-19 on Humanitarian Supply Chains in the world, the Logistics Cluster is compiling updates on entry point for cargo. The table below reflects updates received from other organisations and the private sector. As per the Logistics Cluster mandate, the information gathered focuses only on cargo transport, not passengers’ restrictions. Also note that this list is not exhaustive and will be updated based on the information received on a day-to-day basis. \n  \nShould your organisation be able to provide verified information on cargo entry points, kindly send it to covid-19@logcluster.org(including the source) before 16:00 every day.",
            "country": "NA",
            "clean_url": "reliefweb.int",
            "author": "Logistics Cluster",
            "rights": "You should respect the intellectual property rights of the original source. Please contact the source directly if you want to re-use their content.",
            "link": "https://reliefweb.int/report/world/covid-19-cargo-entry-point-update-9-june-2020",
            "rank": "2714",
            "topic": "NA",
            "language": "en",
            "title": "World: COVID-19 – Cargo Entry Point Update, 9 June 2020",
            "published_date": "2020-06-09 16:04:37",
            "_id": "11e4b6c3a5cb5f0f4bd0cc0cc7881ab1",
            "_score": 4.00863
        },
        {
            "summary": "With  90,787 COVID-19 cases, Maharashtra has reported the highest number of infections",
            "country": "IN",
            "clean_url": "moneycontrol.com",
            "author": None,
            "rights": None,
            "link": "https://www.moneycontrol.com/news/world-news/coronavirus-wrap-june-9-arvind-kejriwal-tests-negative-for-covid-19-eiffel-tower-set-to-reopen-for-publicjune-25_13882861.html",
            "rank": "3986",
            "topic": "business",
            "language": "en",
            "title": "Coronavirus wrap June 9: Arvind Kejriwal tests negative for COVID-19; Eiffel Tower set to reopen for public on June 25",
            "published_date": "2020-06-09 16:03:57",
            "_id": "d0a9f5286d6d56e1acf97ee866af2b14",
            "_score": 4.4296613
        },
        {
            "summary": "The City of Edmonton has cut another 60 employees in a third wave of temporary layoffs amid the COVID-19 pandemic. Interim city manager Adam Laughlin announced the layoffs in a letter to city staff Monday, but didn&#8217;t disclose the positions of impacted workers. &#8220;Temporary layoffs are among the hardest decisions we make, and I appreciate [&#8230;]",
            "country": "NA",
            "clean_url": "edmontonjournal.com",
            "author": "Dustin Cook",
            "rights": None,
            "link": "http://edmontonjournal.com/news/local-news/city-of-edmonton-issues-notices-to-60-employees-in-third-round-of-temporary-covid-19-layoffs",
            "rank": "5600",
            "topic": "news",
            "language": "en",
            "title": "City of Edmonton issues notices to 60 employees in third round of temporary COVID-19 layoffs",
            "published_date": "2020-06-09 16:03:48",
            "_id": "5dd0143c664357634e9f7d44e7adbfd9",
            "_score": 3.9051867
        },
        {
            "summary": "Scientists studying the SARS-CoV-2 coronavirus -- which causes COVID-19 -- believe they've discovered why face masks might help limit transmission of the virus.",
            "country": "NA",
            "clean_url": "upi.com",
            "author": None,
            "rights": "Copyright (c) 2020 United Press International, Inc. All Rights Reserved.",
            "link": "https://www.upi.com/Health_News/2020/06/09/Lab-experiments-show-how-masks-could-protect-against-COVID-19/7041591716956/",
            "rank": "1148",
            "topic": "news",
            "language": "en",
            "title": "Lab experiments show how masks could protect against COVID-19",
            "published_date": "2020-06-09 16:03:45",
            "_id": "35c37b9b51740c7a80b61c0766130ced",
            "_score": 4.4866567
        },
        {
            "summary": "Deputy Commissioner of Mumbai's Brihanmumbai Municipal Corporation, Shirish Dixit on Tuesday succumbed to COVID-19\n \nThe post BMC deputy commissioner Shirish Dixit dies due to coronavirus; 55-yr-old was asymptomatic till Monday evening appeared first on Firstpost.",
            "country": "IN",
            "clean_url": "firstpost.com",
            "author": "FP Staff",
            "rights": None,
            "link": "http://www.firstpost.com/india/bmc-deputy-commissioner-shirish-dixit-dies-due-to-coronavirus-55-yr-old-was-asymptomatic-till-monday-evening-8465741.html",
            "rank": "2357",
            "topic": "news",
            "language": "en",
            "title": "BMC deputy commissioner Shirish Dixit dies due to coronavirus; 55-yr-old was asymptomatic till Monday evening",
            "published_date": "2020-06-09 16:03:27",
            "_id": "fa044163ca696449a2e7cbba6b5e8a38",
            "_score": 3.3516717
        },
        {
            "summary": "People of African descent and other ethnic minorities need better access to culturally relevant health care, if countries are to get a better handle on the Covid-19 pandemic, according to the Pan American Health Organization.",
            "country": "US",
            "clean_url": "cnn.com",
            "author": None,
            "rights": "Copyright (c) 2020 Turner Broadcasting System, Inc. All Rights Reserved.",
            "link": "http://rss.cnn.com/~r/rss/cnn_latest/~3/0bCOMv5av3c/index.html",
            "rank": "54",
            "topic": "NA",
            "language": "en",
            "title": "To slow down the pandemic, minorities in the Americas need better access to health care",
            "published_date": "2020-06-09 16:03:03",
            "_id": "c7dff6d258b3372b989eeb4d5faaab00",
            "_score": 3.7191975
        },
        {
            "summary": "The Lagos State Government has stated that popular Fuji musician, King Wasiu Ayinde Marshall, was not physically present to perform at the recent coronation ceremony",
            "country": "NA",
            "clean_url": "onlinenigeria.com",
            "author": None,
            "rights": "© 2012 Spoonlabs d.o.o.",
            "link": "https://news2.onlinenigeria.com/news/general/834420-covid-19-lagos-clears-air-on-kwam-1%E2%80%99s-performance-at-oba-lawal%E2%80%99s-coronation.html",
            "rank": "111023",
            "topic": "NA",
            "language": "en",
            "title": "COVID-19: Lagos clears air on KWAM 1's performance at Oba Lawal's coronation",
            "published_date": "2020-06-09 16:03:00",
            "_id": "c0acfd1bbd724b62116281a2cbace79a",
            "_score": 2.9601521
        },
        {
            "summary": "New Zealand said Tuesday it will reduce its scientific projects in Antarctica to keep the virtually uninhabited continent free from Covid-19.\n \nThe post New Zealand Cuts Research to Keep Antarctica Virus-Free appeared first on .",
            "country": "NA",
            "clean_url": "courthousenews.com",
            "author": "BARBARA LEONARD",
            "rights": None,
            "link": "https://www.courthousenews.com/new-zealand-cuts-research-to-keep-antarctica-virus-free/?utm_source=rss&utm_medium=rss&utm_campaign=new-zealand-cuts-research-to-keep-antarctica-virus-free",
            "rank": "3920",
            "topic": "NA",
            "language": "en",
            "title": "New Zealand Cuts Research to Keep Antarctica Virus-Free",
            "published_date": "2020-06-09 16:02:50",
            "_id": "cb2faef675bbc582099aa428dfba33ad",
            "_score": 3.4696507
        },
        {
            "summary": "WorkSafeBC has finally shared long-awaited details of its health and safety requirements for B.C. film sets, as Hollywood North prepares to return after COVID-19.",
            "country": "NA",
            "clean_url": "vancouversun.com",
            "author": "Stephanie Ip",
            "rights": None,
            "link": "http://vancouversun.com/news/local-news/covid-19-careful-restart-planned-for-b-c-s-film-industry",
            "rank": "2063",
            "topic": "news",
            "language": "en",
            "title": "COVID-19: B.C.'s film industry gets green light for safe return to set",
            "published_date": "2020-06-09 16:01:23",
            "_id": "ed3eb3d458ce886d4e8c942567e90aff",
            "_score": 4.405679
        },
        {
            "summary": "The Judicial Council of California will consider ending three temporary emergency rules governing evictions, judicial foreclosures and an emergency bail schedule, as California begins a phased re-opening and courts restore services shuttered due to the COVID-19 pandemic. The Judicial Council will consider amending emergency rules that currently stay the issuance ...continue reading\n \nThe post Judicial Council, Chief Justice consider ending some emergency measures as California and Courts expand reopening appeared first on Orange County Breeze.",
            "country": "NA",
            "clean_url": "oc-breeze.com",
            "author": "courtesy",
            "rights": None,
            "link": "http://feedproxy.google.com/~r/OrangeCountyBreeze/~3/3Q4ruoS5k_8/",
            "rank": "155502",
            "topic": "news",
            "language": "en",
            "title": "Judicial Council, Chief Justice consider ending some emergency measures as California and Courts expand reopening",
            "published_date": "2020-06-09 16:01:12",
            "_id": "110d409495a5cdbdddf4f31d07086f02",
            "_score": 2.2187164
        },
        {
            "summary": "Today, the Bob Woodruff Foundation (BWF) announced a total investment of $1.9 million awarded to 13 organizations with programs that serve veterans, service members, and their families. These grants invest in improving veteran and caregiver health and wellness, supporting veteran and military family transition into civilian communities, and addressing the acute and critical needs of veterans impacted by the COVID-19 outbreak.",
            "country": "NA",
            "clean_url": "globenewswire.com",
            "author": None,
            "rights": None,
            "link": "http://www.globenewswire.com/news-release/2020/06/09/2045845/0/en/Bob-Woodruff-Foundation-Announces-1-9-Million-Investment-in-Spring-Grant-Recipients.html",
            "rank": "902",
            "topic": "NA",
            "language": "en",
            "title": "Bob Woodruff Foundation Announces $1.9 Million Investment in Spring Grant Recipients",
            "published_date": "2020-06-09 16:01:00",
            "_id": "c7cc32d50e580f437b6c6498761c8fdc",
            "_score": 3.3578155
        },
        {
            "summary": "A Colorado district attorney announced Tuesday that he found no evidence that the state's health department illegally altered or falsified the death certificates of COVID-19 patients at a Centennial nursing home.",
            "country": "US",
            "clean_url": "denverpost.com",
            "author": "Jessica Seaman",
            "rights": None,
            "link": "https://www.denverpost.com/2020/06/09/colorado-covid-death-certificates-investigation/",
            "rank": "1045",
            "topic": "NA",
            "language": "en",
            "title": "No evidence Colorado health department illegally altered COVID-19 death certificates, DA finds",
            "published_date": "2020-06-09 16:00:49",
            "_id": "87dffedbb20d502cbb2f25a587b87b68",
            "_score": 4.4398503
        },
        {
            "summary": "BAKU &#8212; Azerbaijan has extended coronavirus lockdown restrictions including the closure of borders until July 1, the government said on Tuesday. It said internal flights could resume from June 15 but that all people must stay at home in big cities, including the capital Baku, on June 14 and 15 after the number of COVID-19 [&#8230;]",
            "country": "CA",
            "clean_url": "financialpost.com",
            "author": "Reuters",
            "rights": None,
            "link": "https://business.financialpost.com/pmn/business-pmn/azerbaijan-extends-coronavirus-restrictions-until-july-1",
            "rank": "1898",
            "topic": "news",
            "language": "en",
            "title": "Azerbaijan extends coronavirus restrictions until July 1",
            "published_date": "2020-06-09 16:00:27",
            "_id": "6d080b681740249ee744a34293687914",
            "_score": 3.3396544
        },
        {
            "summary": "PureCare said its proprietary OmniGuard Advance mattress cover has been certified as effective in blocking viruses such as COVID-19.\n \nThe post PureCare mattress cover certified effective in blocking viruses appeared first on Furniture Today.",
            "country": "NA",
            "clean_url": "furnituretoday.com",
            "author": "Perry",
            "rights": None,
            "link": "https://www.furnituretoday.com/bedding-manufacturers/purecare-mattress-cover-certified-effective-in-blocking-viruses/",
            "rank": "38522",
            "topic": "NA",
            "language": "en",
            "title": "PureCare mattress cover certified effective in blocking viruses",
            "published_date": "2020-06-09 16:00:19",
            "_id": "6421da4f54aceedcc70c06c6fc0044c4",
            "_score": 2.9817052
        },
        {
            "summary": "Cost share waivers, set to expire June 30, extended through December 31 \nCost share waivers, set to expire June 30, extended through December 31",
            "country": "NA",
            "clean_url": "globenewswire.com",
            "author": None,
            "rights": None,
            "link": "http://www.globenewswire.com/news-release/2020/06/09/2045838/0/en/Blue-Cross-Blue-Shield-of-Michigan-to-extend-no-cost-benefits-for-COVID-19-treatment-through-year-s-end.html",
            "rank": "902",
            "topic": "NA",
            "language": "en",
            "title": "Blue Cross Blue Shield of Michigan to extend no-cost benefits for COVID-19 treatment through year's end",
            "published_date": "2020-06-09 16:00:00",
            "_id": "d6d20873330d5b3d0e9daff037f1b309",
            "_score": 3.6500182
        },
        {
            "summary": "PARIS — The chief prosecutor of Paris has opened a preliminary investigation of alleged criminal negligence by French government agencies for their handling of the coronavirus crisis.\n \nIn a written statement Tuesday, Paris prosecutor Remy Heitz said 62 legal complaints alleging misconduct have been filed by individuals as well as trade unions and associations.\n \nHeitz says the complaints focus on the criminal offenses of 'endangering the life of others, failing to help someone in danger, voluntary abstention to fight a dangerous disaster, manslaughter and unintentional injuries.\"\n \nSome other legal complaints have been filed across France against care homes and are being investigated locally.\n \nFrance has recorded the deaths of over 14,000 care home residents, or nearly half of the country's total reported pandemic death toll of 29,209.\n \nMore than 70 complaints specifically targeting the government have been filed before the Court of Justice of the Republic, the French court in charge of offenses committed by sitting ministers.\n \n___\n \nHERE'S WHAT YOU NEED TO KNOW TODAY ABOUT THE VIRUS OUTBREAK:\n \n— In poorer regions of the world, easing virus restrictions brings new risks\n \n— The pandemic marks the debut of Chinese companies as global humanitarian donors\n \n— Yemen's rebels crack down as COVID-19 and rumors spread\n \n— Indian American surgeon and his daughter lost to virus were part of a New Jersey family of 5 doctors\n \n— Where do the Tokyo Olympics stand, 2 1/2 months after cancellation?\n \n___\n \nFollow AP pandemic coverage at http://apnews.com/VirusOutbreak and https://apnews.com/UnderstandingtheOutbreak\n \n___\n \nHERE'S WHAT ELSE IS HAPPENING TODAY:\n \nMADRID — The Spanish government says authorities in Morocco and other...",
            "country": "US",
            "clean_url": "seattlepi.com",
            "author": "By The Associated Press",
            "rights": None,
            "link": "https://www.seattlepi.com/news/article/The-Latest-UAE-capital-extends-virus-lockdown-15326233.php",
            "rank": "2154",
            "topic": "NA",
            "language": "en",
            "title": "The Latest: Paris prosecutor opens probe of govt agencies",
            "published_date": "2020-06-09 15:59:40",
            "_id": "c994aa1c4f24323a93f63a0be9e9b736",
            "_score": 2.027432
        },
        {
            "summary": "Alberta Premier Jason Kenney will give an update on preparations and timing for the second stage of the province&#8217;s relaunch at 12:30 p.m. Kenney will be joined by Health Minister Tyler Shandro and Dr. Deena Hinshaw, the province&#8217;s chief medical officer of health. The second stage of relaunch could potentially allow the reopening of schools, [&#8230;]",
            "country": "NA",
            "clean_url": "edmontonjournal.com",
            "author": "Ashley Joannou",
            "rights": None,
            "link": "http://edmontonjournal.com/news/politics/covid-19-kenney-to-give-update-on-albertas-relaunch-plans-at-1230-p-m",
            "rank": "5600",
            "topic": "news",
            "language": "en",
            "title": "COVID-19: Kenney to give update on Alberta's relaunch plans at 12:30 p.m.",
            "published_date": "2020-06-09 15:59:18",
            "_id": "55d0dc652369bc92c42aec8ee78ed495",
            "_score": 3.1564984
        },
        {
            "summary": "A grim economic outlook amid an ever-growing spread of the Covid-19 pandemic has turned consumers jittery",
            "country": "NA",
            "clean_url": "business-standard.com",
            "author": None,
            "rights": "Copyright www.business-standard.com",
            "link": "https://www.business-standard.com/article/current-affairs/slowdown-blues-post-lockdown-consumer-confidence-remains-low-120060901596_1.html",
            "rank": "1636",
            "topic": "NA",
            "language": "en",
            "title": "Slowdown blues: Post-lockdown, consumer confidence remains low",
            "published_date": "2020-06-09 15:59:00",
            "_id": "d1d2dfa892c4b4a01417cace2a1f93f0",
            "_score": 3.9324322
        },
        {
            "summary": "Authorities have added 45 new deaths reported in the past 24 hours after days of steady decline",
            "country": "CA",
            "clean_url": "theglobeandmail.com",
            "author": "",
            "rights": "2020 The Globe and Mail Inc.",
            "link": "https://www.theglobeandmail.com/canada/article-number-of-deaths-linked-to-covid-19-surpasses-5000-in-quebec/?cmpid=rss",
            "rank": "526",
            "topic": "news",
            "language": "en",
            "title": "Number of deaths linked to COVID-19 surpasses 5,000 in Quebec",
            "published_date": "2020-06-09 15:58:35",
            "_id": "c8ffc11a4f0860e5ba0972dd396fa035",
            "_score": 3.9916997
        },
        {
            "summary": "Health experts are disputing an assertion from the World Health Organization that the spread of COVID-19 by asymptomatic carriers is \"very rare.\" New York pediatrician Dr. Dyan Hes joined CBSN to discuss the concerns and how you can keep your kids safe this summer.",
            "country": "US",
            "clean_url": "cbsnews.com",
            "author": None,
            "rights": None,
            "link": "https://www.cbsnews.com/video/coronavirus-covid-19-asymptomatic-spread-world-health-organization-dr-dyan-hes/",
            "rank": "213",
            "topic": "news",
            "language": "en",
            "title": "Doctor weighs in on risk of asymptomatic spread of coronavirus",
            "published_date": "2020-06-09 15:57:58",
            "_id": "56468988157567786db5cd61eb495185",
            "_score": 3.6290176
        }
    ],
    "user_input": {
        "q": "covid",
        "search_in": "title_summary_en",
        "lang": "en",
        "country": None,
        "from": "2020-06-01 00:00:00",
        "to": None,
        "ranked_only": "True",
        "from_rank": None,
        "to_rank": None,
        "sort_by": "date",
        "page": 1,
        "size": 50,
        "sources": None,
        "not_sources": [
            "dailymail.co.uk"
        ],
        "topic": None
    }
}